config/routes.rb
Site::Application.routes.draw do

  resources :images
  resources :ideas
  resources :me, only: :index
  resources :debug, only: :index
  devise_for :users

  root to: "ideas#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :description, :title
  has_many :images
  has_and_belongs_to_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :idea_id, :image
  belongs_to :idea
  mount_uploader :image, ImageUploader
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :done, :idea_id, :parent_task_id, :title

  belongs_to :idea
  has_many :children, foreign_key: "parent_task_id", class_name: "Task"
  belongs_to :parent, foreign_key: "parent_task_id", class_name: "Task"

  validates_presence_of :idea

  def self.top_level_for idea
    where(idea_id: idea.id, parent_task_id: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_and_belongs_to_many :ideas

  def admin?
    email == "dan2552@gmail.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/debug_controller.rb
class DebugController < ApplicationController

  def index
    raise "oops"
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  authorize_resource

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/me_controller.rb
class MeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin?
    current_user.try(:email) == "dan2552@gmail.com"
  end

  def button text, url, cls=""
    link_to(url, class: "btn btn-large btn-primary #{cls}") do
      text
    end
  end

end

app/helpers/debug_helper.rb
module DebugHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper

  def idea_image idea
    image_url = idea.images.sample.try(:image_url) || "squared_paper.png"
    image_tag(image_url)
  end

  def idea_user_count idea
    count = idea.users.count
    return '' if count == 0
    ("<span class=\"fui-man-16\"></span>#{count}").html_safe
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Destroy', @idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/ideas/index.html.erb
<div class="row">
  <p class="pull-right">
    <%= button "New idea", new_idea_path if can? :manage, Idea %>
  </p>
</div>

<div class="row-fluid span12">
  <% @ideas.each do |idea| %>
      <%= render template: 'ideas/show', locals: {idea: idea} %>
  <% end %>
</div>
</div>
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<% idea = idea || @idea %>

<div class="tile span6 left-align animated flipInX">
  <div class="row pull-left">
    <div class="circle-image hidden-phone">
      <%= idea_image(idea) %>
    </div>
  </div>
  <h3 class="pull-right">
    <small><%= idea_user_count(idea) %></small>
  </h3>
  <h1><%= idea.title %></h1>
  <p><small><%= idea.description %></small></p>
  <% total = 0 %>
  <% percent = 0 %>

  <div class="task-progress span6">
    <h3 class="tile-title">Tasks <small>(<%= percent %>/<%= total %>)</small></h3>
    <div class="progress">
      <div class="bar" style="width: <%= (percent / total.to_f) * 100 %>%;">
      </div>
    </div>
  </div>
</div>

app/views/images/_form.html.erb
<%= simple_form_for(@image) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= image_tag(@image.image_url) if @image.image? %>
    <%= f.file_field :image %>
    <%#= f.hidden_field :image_cache %>
    <%= f.collection_select(:idea_id, Idea.all, :id, :title) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Idea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.image %></td>
    <td><%= image.idea_id %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @image.image %>
</p>

<p>
  <b>Idea:</b>
  <%= @image.idea_id %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error"%> animated wobble">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Daniel Green", root_path, class: 'brand' %>
  </li>
  <li>
    <%= link_to "Me", me_index_path, class: "top-menu" %>
  </li>
  <li>
    <%= link_to "Collaborate", root_path, class: "top-menu" %>
  </li>
</ui>

<!--
</li>
<li>
<%= link_to "Ideas", ideas_path, class: "top-menu" %>
</li>
<li>
<%= link_to "Me", ideas_path, class: "top-menu" %>
</li>
</ul>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dan2552" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dan2552" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <h1 class="logo">Dan2552<small>ideas and experiments</h1>
    <div id="main" role="main">
      <div id="secondaryContainer" class="container hidden">
        <div class="content">
          <div class="row">
            oh, hello
          </div>
        </div>
      </div>
      <div id="primaryContainer" class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          <% if params[:controller] + params[:action] == "ideasindex" %>
          <div id="footerContainer" class="container">
            <div class="row">
              <div class="span8">
                <h3 class="footer-title">About Me</h3>
                <p>I studied Computer Science at University of Portsmouth; awarded the David Callear Memorial Prize for the Best Graduate Project in the field of Educational Technology for my final year project, a mobile application for the University of Portsmouth Library.
                </p>
                <p>
                I have always been interested in technology and programming, with a recent obsession for mobile based development (iOS and Android) and Ruby on Rails since working at <a href="http://dev.alliants.co.uk">Alliants</a>. Keen on gadgets and technology, I own a multitude of Apple devices and Android phones.
                </p>
              </div>

              <div class="span4">
                <div class="footer-banner">
                  <div class="pad">
                    <div class="browser-author"></div>
                  </div>

                  <div class="pad">
                  <a class="btn btn-danger btn-large btn-block" href="http://twitter.com/Dan2552" target="_blank">
                    <span class="fui-plus-16"></span> Follow me on Twitter
                  </a>
                  <a class="btn btn-danger btn-large btn-block" href="http://uk.linkedin.com/in/dan2552" target="_blank">
                  <span class="fui-eye-16"></span> View my Linkedin profile
                  </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>